# Generated by Django 3.1.7 on 2021-04-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_visitor_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
