# Generated by Django 3.1.7 on 2021-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
