# Generated by Django 3.1.7 on 2021-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20210331_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsite',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
